### PR TITLE
Updated dependency versions.

### PR DESCRIPTION
**Pull request by azriel91**
Hiya, I've bumped some dependency versions. It compiles, but I haven't got Wayland to test that it works at runtime.

p/s: if it does work, could you please do a release as well? Thank you!

### CODE REVIEW

**Comment by azriel91** [comment]
Heya @trimental, would this be able to be merged and released?

**Comment by azriel91** [comment]
By the way, if you're open to myself becoming a maintainer, I'm happy to take this.

**Comment by trimental** [comment]
@azriel91 At present I'm pretty busy with school so I'd love for someone to keep maintenance actually :)

**Comment by trimental** [comment]
@azriel91 if you can keep the package up to date and working correctly I'll be happy to release the changes once I've tested them.

**Comment by azriel91** [comment]
Cool, so the `test` example compiles, but my system doesn't run wayland. Could you check if this works as expected:

```bash
git remote add azriel91 git@github.com:azriel91/andrew.git
git fetch azriel91 maintenance/update-dependencies
git checkout maintenance/update-dependencies
cargo run --example test
```

`window.new_seat(..)` isn't called anymore as according to the [`smithay-client-toolkit` changelog](https://github.com/Smithay/client-toolkit/blob/master/CHANGELOG.md#070----2020-02-07) it's automatically tracked.

**Comment by trimental** [comment]
@azriel91 seems to be working well for me. When you ready we can merge this and then release, thanks for your work :)

**Comment by azriel91** [comment]
Sweet thanks :v:!

**Pull request merged**
